### ISSUE TITLE
Sales Suggestions

### ISSUE THREAD

**Issue by PrenSJ2** [tutorcruncher/hermes#20]
Add to MetaAgencySerilializer:
	have_saved_card_details
	trial_expiry_date

**Comment by FionnFinegan** [comment]
New field to be populated on Pipedrive with the client manager from Meta.

Field name:
support_client_manager

Accepted values:
raashi_thakran
maahi_islam

**Comment by PrenSJ2** [comment]
Sam Linge 
Would like to have both startup and payg go into one pipeline (this is fine as we just set the same default pipeline for these)
but would also like if we could apply a specific label to allow him to identify what is startup and what is payg

**Comment by sam-linge** [comment]
Current workflow: I am manually checking in Meta to see agency's paid invoice count and manually updating `paid_invoice_count` in Pipedrive, which then triggers an automation.

If Hermes could automatically update that field when the paid invoice count goes up then it would be a huge timesave.

**Comment by sam-linge** [comment]
Another one for the wish list - would it be possible to have Pipedrive delete deals when a certain label is applied to the company's meta profile? Less pressing but since Hermes is up and running I have to remove narcs from my Pipedrive ontop of marking them off in Meta.

**Comment by sam-linge** [comment]
We have all of these fields that mirror the fields found on Meta - presumably these will be autofilled? Filling all of these in for every deal that comes through would be insanely laborious: 
![image](https://github.com/tutorcruncher/hermes_v2/assets/24611156/46d7cd6a-3ec1-4dd1-a7f0-68cf2bfdd45a)

**Comment by sam-linge** [comment]
I'm not 100% on what we can grab from the Google Meet demo calls, but if there could be some way by which attendance/non-attendance can be recorded and used to automatically update the 'Attended call?' field in Pipedrive then that would be 🔥

**Comment by sam-linge** [comment]
Could we also pull across the client manager from meta into Pipedrive?

**Comment by sam-linge** [comment]
Could we also pull across the trial expiry date and estimated monthly income (or some indication of their price plan)?

**Comment by PrenSJ2** [comment]
if Call Booked with Sales & Company exists  ==> Do nothing / create Meeting
If Call Booked with Sales and Company doesn't exist ==> create Org -> Lead  (Not Deal)
if TC Signup ==> create Org and Deal
