### ISSUE TITLE
Deal not being made for persons booking call through call booker

### ISSUE THREAD

**Issue by gabegatrill** [tutorcruncher/hermes#270]
Noticed in the PM (29/08) that a deal was not being created for "bemeasalways@gmail.com" (https://tutorcruncher.pipedrive.com/person/7162) when I booked her in through Sam's call booker. 

I then tried this once more (with the same email address) and still no deal was created. 

Pipedrive registered the activity (call booked).

**Comment by PrenSJ2** [comment]
I just tried this, and it worked for me. be sure that you look in the Onboarding (NEW) pipeline, Booked Call stage; as Sam has an automation to move it there

**Comment by PrenSJ2** [comment]
Is related to #263
