### ISSUE TITLE
Deals are being reopened when closed.

### ISSUE THREAD

**Issue by sam-linge** [tutorcruncher/hermes#277]
https://tutorcruncher.pipedrive.com/deal/6536
https://tutorcruncher.pipedrive.com/deal/6532
https://tutorcruncher.pipedrive.com/deal/6481

You can try it yourself on any of the duplicate deals.

**Comment by sam-linge** [comment]
Same is happening when I mark a deal as 'lost': https://tutorcruncher.pipedrive.com/deal/6365

**Comment by PrenSJ2** [comment]
due to #283 and #282
