### ISSUE TITLE
Call booker disappearing before the link even expires

### ISSUE THREAD

**Issue by RaashiThakran** [tutorcruncher/hermes#29]
<img width="717" alt="Screenshot_56" src="https://github.com/tutorcruncher/hermes_v2/assets/134603227/7707bcd4-7564-48a4-8a93-8ea7a18a26df">

**Comment by RaashiThakran** [comment]
https://tutorcruncher.com/book-a-call/v2/4/?s=4db9bf28e1dc3053e8019800d75176ce83e74957&admin_id=4&company_id=69&e=1697446847

**Comment by HenryTraill** [comment]
may have been a one off, monitoring

**Comment by PrenSJ2** [comment]
this seems to be caused when a user has old / incorrect localStorage data for the form

Solution:

1. Right Click > Inspect > Console Tab
2. type this
3. `localStorage.clear()`
4. press enter
5. refresh page
