### ISSUE TITLE
Call-booker error

### ISSUE THREAD

**Issue by gabegatrill** [tutorcruncher/hermes#290]
Currently, call-booker availability is limited due to the way it reacts to overlapping meetings. 

Example: 

- Sam has a meeting that finishes at 2pm, with the next starting at 2.30pm. 
- 2pm is not available on call-booker as it has registered that at 2.00pm exactly he is busy, and also exactly at 2.30pm he is busy. 

In reality, Sam has a 30 minute gap at 2 that people should be able to book in. 

The current fix is if I change his first meeting to finish at 1.59pm, and his next meeting to begin at 2.31pm, 2pm then opens up in the call-booker.

**Comment by FionnFinegan** [comment]
Let me know once we have this changed pls, I'm going to re-instate a 15 minute buffer period in the interim time but I'll remove it when we don't need it anymore.

**Comment by tomhamiltonstubber** [comment]
This is now fixed
